name: CI Check

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 21
    - name: Build
      run: KSTOREFILE=../key.store KSTOREPWD=${{ secrets.KSTOREPWD }} KEYALIAS=${{ secrets.KEYALIAS }} KEYPWD=${{ secrets.KEYPWD }} ./gradlew assembleFreeDebug
    - name: Spotless Check
      run: ./gradlew spotlessCheck
    - name: Run tests
      run: ./gradlew testFreeDebug || true
    - name: Build with Gradle
      run: find -type f -name '*.apk'
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Debug
        path: app/build/outputs/apk/free/debug

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: vlatest
        files: app/build/outputs/apk/free/debug/*.apk
